# Generated by Django 4.2.7 on 2023-12-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.IntegerField(choices=[(0, 'Kilogram'), (1, 'Gram'), (2, 'Litre'), (3, 'Piece')], default=1),
        ),
    ]
